# Depth Anything V2 API Server Configurations

# Local development server (no authentication)
depth-anything-v2-local:
  base_url: "http://localhost:8000"
  api_key: null
  model: "depth-anything-v2"
  description: "Local development server"

# Lab server (replace with your actual server details)
depth-anything-v2-lab:
  base_url: "http://your-lab-server:8000"  # Replace with actual server URL
  api_key: "sk-your-api-key-here"  # Replace with your API key
  model: "depth-anything-v2"
  description: "Lab server with authentication" 